### ISSUE TITLE
Server Source Code

### ISSUE THREAD

**Issue by Elqul** [EverestOpenSource/Everest-iOS#1]
Hello,

is their anyway i can have the server source code ? as it seems this app can only work with the server code .

Thank You

**Comment by iwasrobbed** [comment]
Hi @Elqul, the server code is not available as it was not allowed to be open sourced at the time. Apologies for this, but it shouldn't be too difficult to create something similar given the sample mock responses you have available in the test code (e.g. https://github.com/EverestOpenSource/Everest-iOS/tree/master/KIF/Mocks/Mock%20Base%20Classes)
